#sudo ansible-playbook -i ../hosts 99-deletevm.yaml -e hostname="dns,master,installer,node" -v


- name: Unsubscribe the Virtual Machine
  hosts: "{{ hostname }}"
  serial: 1
  tags:
    - unsubscribe
  tasks:
    - name: UnSubscribe to access.redhat.com
      redhat_subscription:
        state: absent
        username: "{{ redhat_username }}"
        password: "{{ redhat_password }}"
        pool: "{{ redhat_pool }}"
        force_register: yes

- name: shutdown the Virtual Machine
  hosts: "{{ hostname }}"
  connection: local
  serial: 1
  tags:
    - shutdownvm
  tasks:
    - name: shutdown {{inventory_hostname}}
      shell: virsh shutdown {{inventory_hostname}}
    - pause:
        seconds: 15

- name: delete the Virtual Machine
  hosts: "{{ hostname }}"
  connection: local
  serial: 1
  tags:
    - deletevm
  tasks:
    - name: delete {{inventory_hostname}} node
      shell: virsh undefine {{inventory_hostname}} --remove-all-storage
