---
# tasks file for dns
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest
- name: Enable service dnsmasq, and not touch the running state
  service:
    name: dnsmasq
    enabled: yes
- name: start service dnsmasq
  service:
    name: dnsmasq
    state: started

- name: making entry in /etc/dnsmasq.conf
  blockinfile:
    path: /etc/dnsmasq.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      strict-order
      domain-needed
      local=/sandbox.com/
      bind-dynamic
      log-queries
      address=/.app.sandbox.com/192.168.122.34


#- name: making entry in /etc/dnsmasq.conf -1
#  shell: echo -e strict-order >> /etc/dnsmasq.conf

#- name: making entry in /etc/dnsmasq.conf -2
#  shell: echo -e domain-needed >> /etc/dnsmasq.conf

#- name: making entry in /etc/dnsmasq.conf -3
#  shell: echo -e "local=/example.com/" >> /etc/dnsmasq.conf

#- name: making entry in /etc/dnsmasq.conf -4
#  shell: echo -e bind-dynamic >> /etc/dnsmasq.conf

#- name: making entry in /etc/dnsmasq.conf -5
#   shell: echo -e log-queries >> /etc/dnsmasq.conf

#- name: making entry in /etc/dnsmasq.conf -6
#  shell: echo -e "address=/.app.sandbox.com/192.168.122.34" >> /etc/dnsmasq.conf

- name: making entry in /etc/sysconfig/network-scripts/ifcfg-eth0
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      IPADDR="{{ipadresstoset}}"
      NETMASK="255.255.255.0"
      GATEWAY="192.168.122.1"
      PEERDNS="no"
      PEERROUTES="yes"
      IPV6_PEERDNS="no"
      IPV6_PEERROUTES="yes"
      DNS1="192.168.122.1"


- name: changing from dhcp to none
  shell: sed -i -- 's/dhcp/none/' /etc/sysconfig/network-scripts/ifcfg-eth0


#- name: making entry in /etc/hosts
#  blockinfile:
#    path: /etc/hosts
#    block: |
#      {{ hostvars[item]['ipadresstoset'] }} {{ hostvars[item]['inventory_hostname'] }} {{ hostvars[item]['shortname'] }}
#  with_items:
#     - {{ groups[master] }}
#     - {{ groups[installer] }}
#     - {{ groups[node] }}
#     - {{ groups[dns] }}

- name: making entry in etc-hosts
  shell: echo -e "{{ hostvars[item]['ipadresstoset'] }} {{ hostvars[item]['inventory_hostname'] }} {{ hostvars[item]['shortname'] }}" >> /etc/hosts
  with_items:
     - "{{ groups['master'] }}"
     - "{{ groups['installer'] }}"
     - "{{ groups['node'] }}"
     - "{{ groups['dns'] }}"


- name: making entry in /etc/ssh/sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      UseDNS no

#- name: making entry in sshd_config
#  shell: echo -e "UseDNS no" >> /etc/ssh/sshd_config

- name: making IPTABLE entry-tcp
  shell: iptables -I INPUT -s 192.168.122.0/24 -p tcp --dport 53 -j ACCEPT
- name: making IPTABLE entry-udp
  shell: iptables -I INPUT -s 192.168.122.0/24 -p udp --dport 53 -j ACCEPT

- name: Creating effective iptables_rules
  shell: iptables-save > /etc/iptables_rules
- name: script for iptables_rules
  shell: echo "/sbin/iptables-restore < /etc/iptables_rules" >> /etc/rc.local
- name: script for iptables_rules
  shell: chmod +x /etc/rc.d/rc.local
