---
# tasks file for dns
- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: latest
- name: Enable service dnsmasq, and not touch the running state
  service:
    name: dnsmasq
    enabled: yes
- name: start service dnsmasq
  service:
    name: dnsmasq
    state: started

- name: making entry in /etc/dnsmasq.conf -1
  shell: echo -e strict-order >> /etc/dnsmasq.conf

- name: making entry in /etc/dnsmasq.conf -2
  shell: echo -e domain-needed >> /etc/dnsmasq.conf

- name: making entry in /etc/dnsmasq.conf -3
  shell: echo -e "local=/example.com/" >> /etc/dnsmasq.conf

- name: making entry in /etc/dnsmasq.conf -4
  shell: echo -e bind-dynamic >> /etc/dnsmasq.conf

- name: making entry in /etc/dnsmasq.conf -5
  shell: echo -e log-queries >> /etc/dnsmasq.conf

- name: making entry in /etc/dnsmasq.conf -6
  shell: echo -e "address=/.app.sandbox.com/192.168.122.34" >> /etc/dnsmasq.conf

- name: making a static ip
  shell: echo -e "IPADDR=\"{{ipadresstoset}}\"\nNETMASK=\"255.255.255.0\"\nGATEWAY=\"192.168.122.1\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0

- name: changing from dhcp to none
  shell: sed -i -- 's/dhcp/none/' /etc/sysconfig/network-scripts/ifcfg-eth0

- name: making entry in ifcfg-eth0 -1
  shell: echo -e "PEERDNS=\"no\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0

- name: making entry in ifcfg-eth0 -2
  shell: echo -e "PEERROUTES=\"yes\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0

- name: making entry in ifcfg-eth0 -3
  shell: echo -e "IPV6_PEERDNS=\"no\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0

- name: making entry in ifcfg-eth0 -4
  shell: echo -e "IPV6_PEERROUTES=\"yes\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0

- name: making entry in ifcfg-eth0 -5
  shell: echo -e "DNS1=\"192.168.122.1\" " >> /etc/sysconfig/network-scripts/ifcfg-eth0




- name: making entry in etc-hosts
  shell: echo -e "{{ hostvars[item]['ipadresstoset'] }} {{ hostvars[item]['inventory_hostname'] }} {{ hostvars[item]['shortname'] }}" >> /etc/hosts
  with_items:
     - "{{ groups['master'] }}"
     - "{{ groups['installer'] }}"
     - "{{ groups['node'] }}"
     - "{{ groups['dns'] }}"


- name: making entry in sshd_config
  shell: echo -e "UseDNS no" >> /etc/ssh/sshd_config

- name: making IPTABLE entry-tcp
  shell: iptables -I INPUT -s 192.168.122.0/24 -p tcp --dport 53 -j ACCEPT
- name: making IPTABLE entry-udp
  shell: iptables -I INPUT -s 192.168.122.0/24 -p udp --dport 53 -j ACCEPT

- name: Creating effective iptables_rules
  shell: iptables-save > /etc/iptables_rules
- name: script for iptables_rules
  shell: echo "/sbin/iptables-restore < /etc/iptables_rules" >> /etc/rc.local
- name: script for iptables_rules
  shell: chmod +x /etc/rc.d/rc.local
