---
# tasks file for common
- name: changing from dhcp to none
  shell: sed -i -- 's/dhcp/none/' /etc/sysconfig/network-scripts/ifcfg-eth0



- name: making entry in /etc/sysconfig/network-scripts/ifcfg-eth0
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ipadresstoset}}"
    block: |
      IPADDR="{{ipadresstoset}}"
      NETMASK="255.255.255.0"
      GATEWAY="192.168.122.1"
      PEERDNS="no"
      PEERROUTES="yes"
      IPV6_PEERDNS="no"
      IPV6_PEERROUTES="yes"


- name: Adding DNS entry
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      DNS1="{{ hostvars[item]['ipadresstoset'] }}"
      DOMAIN="sandbox.com"
  with_items:
     - "{{ groups['dns'] }}"


- name: making entry in /etc/ssh/sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      UseDNS no
